# Use Trusty beta environment: https://docs.travis-ci.com/user/trusty-ci-environment/
dist: trusty
sudo: false

language: node_js
node_js:
  - '4'
  - '6'
  - 'stable'
cache: yarn

# Make Greenkeeper work with lockfiles:
# https://github.com/greenkeeperio/greenkeeper-lockfile/tree/f62f2f3e33cd1dd349c2898e0129c693cbc5804d#yarn
env:
  global:
    secure: 2C0uCwTHVZdgaxsi+Eoqe7KwF1Xq4ucrPrKfpzkXlkLH5LMlEtwAWhFeBJVW1nmAcVE9063AqS6QMpO5jTf5RQuxdXJ0rOeqTgD1cHPnP5Ydqh8b8OqFw0ei+D0wc5sNvTTxNs9FoyBTYci7xuyx4b2jNczZTNlaMpFwfDNe6rC2RI1Cko38QcXjHkP010v9FnPgBOuS27geFwgAT+BW/bv1OBmtNsZXY3FIBk35mrhqQls856PUwYgAv86OCgat4APHrGhqU/myCTtEoB1AFH6VCAadhuvtcHZzMSykidcU4qJxfIk7uGDQhVeUSo01MVvKINIyoRc8QwyqMi3UqWbq1YSuo9WJOLmrVj5WsxzNT0oxKUlScWIHZedOmR1bBu3S/d6Qf+8krbw8XuqalFQ4n8cV7UXri6RBJB+uZaMa+oEVo0OQEkH4o71LW5l9CkedWSiLGFgRJawKawhGb8Vp4uIoPG9pZMcW8NyWf3MXAxwNbJ285rHXmqbtVyVETosNWwUtwdBaBkgktprE3JjD2tBAkdOCXt5csMuU2E4Q8Ws5SmFK1uhRtzfSvcCmvWTkq6gaK5siL107uPyerX3++HWestVo6eJuCnSmyYsKGxAbUNIIq8UJjd/JtELodcsHNh0XV/kcjx7Bh9uqi43hKS9yTK4BFD/ZOM8fN4I=

before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
