# Use Trusty beta environment: https://docs.travis-ci.com/user/trusty-ci-environment/
sudo: required
dist: trusty

env:
  global:
    secure: 7pneH1d+volx2kQ0WAt1nddY5zT0vz5sSS49tusssPuB0qDEnXshhVvZ6lcIcxD8ciys0aLLlimlX2A325VZzo57IuI4TuMwWE58cBAWUjsxbvxXRBrUQ0xA0mB9kVuzGDPbHruqnUxOPOXgkzEBJK4WXoq41s3PaUHFSfRJxDj4hb5z5HV/JpwJZMV7fahLUhyka81QJKdp9E/3/P4MQrTgeprVubhWkrdOeMaKbz/iZjsb3aqnFYrmaOQXWOq5umfUTRKbBHFo1x3EI8Rn36ICGtoW6+AQ/bSvPahv2mPJYJUQgbEY6A6NNiFVIpFeqeNBmB8cO8VVLYpQsRrS7cb7wH/VnPlEIyK8mKHV7KVtoV8KY8kGa90wyY6hyjvwbX0sNS4y/m6EQEZVRAaJzrx+zqGV8b7x9xk0RzhmAVFxJtUZ689A3lCP+AIPAXTVFinB/ap9fkUoWjmW1GsaMGb1CQ/4obKyD/ZJdpBVs4JX4nuNg5cQGlezmyH9COnl0ueIY1dVpXh37bk8PQw9hsIzRQu46Vysh3tOtfWEFUZdXThzynLW6GLgKAE2c7kPEyy/aVIHFRg6MBoGXbEGFZt5spHAbgdiVBoU+MVlXD95rcNJkznQk2KQI4fmMPd8SJm+5TZD33oPQPuICK2G0dQwnLzjfqtT/p7x2cqU83A=

language: node_js
node_js:
  - '4'
  - '6'
  - 'stable'
cache: yarn
after_success:
  - ./yarn.sh
